# Generated by Django 3.0.2 on 2020-04-08 07:22

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.CharField(default=0, max_length=10, verbose_name=django.contrib.auth.models.User),
        ),
    ]
