# Generated by Django 3.0.2 on 2020-04-09 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0007_auto_20200409_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('score', models.OneToOneField(default=0, max_length=1000, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='score',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
